name: CI Node.js unit test
run-name: Run nodejs unit test 

on:
 push:
  branches: [main]

jobs:
 run_unit_test:
  name: nodejs unit test
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

    - name: Caching dependencies
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-CACHE-${{ hashFiles('**/package-lock.json') }}

    - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
      name: Setup Node.js
      uses: actions/setup-node@v3
      with:
       node-version: 16

    - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
      name: Install dependencies
      run: npm ci

    - name: Do unit testing
      run: npm test